#include "lexer.h"
#include "parser.h"
#include <time.h>

int main(int argc, char* argv[]){
    printf("\nStage 1 - Implementation Status\n");
    printf("> Grammar loads dynamically from grammar.txt\n");
    printf("> First and follow set computation automated by code\n");
    printf("> Both lexical and syntax analysis modules implemented\n\n");
    printf("********************************\n\n");

    if(argc!=3){
        printf("Please re-enter command as ./stage1exe testcase.txt parsetreeOutFile.txt\n");
        return 0;
    }

    Grammar *g = loadGrammar("grammar.txt");
    printf("> Grammar loaded.\n");
    // printGrammar(g);
    
    // if(argc > 1){
    //     removeComments(argv[1],"out.txt");
    //     printTokenList(argv[1]);
    // }
    FirstAndFollow* ff = getFirstAndFollowSets(g);
    printf("> First and follow sets computed.\n");
    // printFirstAndFollow(ff);
    ParsingTable pt = makeNewParseTable();
    createParseTable(g, ff, pt);
    printf("> Parse table created.\n\n");
    // printParsingTable(pt);
    printf("********************************\n\n");
    int loop = 1;
    while(loop){
        printf("Enter the task to perform.\n\n");
        printf("0 - Quit\n");
        printf("1 - Remove comments from the input code and print\n");
        printf("2 - Print the token list generated by the lexer\n");
        printf("3 - Parse to verify the syntactic correctness of the input code and print the parse tree appropriately\n");
        printf("4 - Print the total time taken by Stage 1 of the compiler\n\n");
        
        int op;
        scanf("%d", &op);

        switch(op){
            case 0:
                loop = 0;
                break;
            case 1:
                printf("\n>> Removing comments.\n");
                removeComments(argv[1], "out.txt");
                printf("Comments removed, output sent to out.txt.\n");
                break;
            case 2:
                printf("\n>> Printing token list.\n");
                printTokenList(argv[1]);
                break;
            case 3:
                ParseTree tree = parseInputSourceCode(argv[1],pt,ff,&errors);
                printParseTree(tree, argv[2]);
                // printf("\n>>Printing parsing table.\n");
                // printParsingTable(pt);
                break;
            case 4:
                printf("\n>>Beginning timing.\n");
                
                clock_t start_time, end_time;
                double total_CPU_time, total_CPU_time_in_seconds;
                start_time = clock();

                // invoke your lexer and parser here
                Grammar *g2 = loadGrammar("grammar.txt");
                printf("> Grammar loaded.\n");
                FirstAndFollow* ff2 = getFirstAndFollowSets(g2);
                printf("> First and follow sets computed.\n");
                ParsingTable pt2 = makeNewParseTable();
                createParseTable(g2, ff2, pt2);
                printf("> Parse table created.\n\n");
                // invoke parse tree fn here

                end_time = clock();
                total_CPU_time  =  (double) (end_time - start_time);
                total_CPU_time_in_seconds =   total_CPU_time / CLOCKS_PER_SEC;

                printf("Total time taken = %f cycles = %f seconds\n", total_CPU_time, total_CPU_time_in_seconds);
                break;

                // Print both total_CPU_time and total_CPU_time_in_seconds 

            default:
                printf("Invalid argument, please try again.\n");

        }

    }
    return 0;
}